package shenhe;

import shenhe.command.Command;
import shenhe.parser.Parser;

/**
 * Represents the main entry point for the Shenhe application.
 * <p>
 * The {@code Shenhe} class is responsible for initializing and running the application.
 * It handles loading tasks from storage, reading user commands, executing commands,
 * and managing the application state.
 * </p>
 */
public class Shenhe {

    private final Storage storage;
    private TaskList tasks;
    private final Ui ui;

    /**
     * Constructs a {@code Shenhe} object with the specified file path for storing tasks.
     * <p>
     * Initializes the user interface, storage, and loads the tasks from the specified file.
     * If loading tasks fails, an empty task list is initialized.
     * </p>
     *
     * @param filePath The path to the file where tasks are stored.
     */
    public Shenhe(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        try {
            tasks = storage.loadTasks();
        } catch (Exception e) {
            ui.showLoadingError();
            tasks = new TaskList();
        }
    }

    /**
     * Processes the given user input and returns Shenhe's response.
     * <p>
     * This method parses the user's input into a command and executes it, returning the response
     * generated by the command. If an error occurs during parsing or execution, an error message
     * is returned.
     * </p>
     *
     * @param input The user's input command as a string.
     * @return Shenhe's response as a string, or an error message if an exception occurs.
     */
    public String getResponse(String input) {
        try {
            Command c = Parser.parse(input);
            return c.execute(tasks, ui, storage);
        } catch (Exception e) {
            return "Error: " + e.getMessage();
        }
    }

    /**
     * Returns the welcome message for the Shenhe application.
     * <p>
     * This method provides the initial welcome message that is displayed to the user when the
     * application starts.
     * </p>
     *
     * @return The welcome message as a string.
     */
    public String getWelcomeMessage() {
        return ui.showWelcome();
    }
}
