package kobe.util;

import kobe.task.TaskList;

import java.util.Scanner;

/**
 * Handles the user interface for the Kobe chatbot application.
 */
public class Ui {
    private final Scanner scanner;
    private String latestResponse;

    /**
     * Constructs a Ui object and initializes the scanner for reading user input.
     */
    public Ui() {
        scanner = new Scanner(System.in);
        latestResponse = "";
    }

    /**
     * Returns the welcome message.
     *
     * @return The welcome message.
     */
    public String getWelcomeMessage() {
        String logo =
                " K   K   OOO   BBBB   EEEE  \n" +
                        " K  K   O   O  B   B  E     \n" +
                        " KKK    O   O  BBBB   EEEE  \n" +
                        " K  K   O   O  B   B  E     \n" +
                        " K   K   OOO   BBBB   EEEE  \n";

        latestResponse = "____________________________________________________________\n"
                + "Greetings from Kobe Bryant. \n" + logo
                + "How can I help you, my man?\n"
                + "____________________________________________________________";
        return latestResponse;
    }

    /**
     * Displays an error message indicating that there was an error loading the task list.
     */
    public void showLoadingError() {
        latestResponse = "OOPS!!! There was an error loading your task list.";
    }

    /**
     * Sets the latest response generated by the Ui.
     * @param response The response to set.
     */
    public void setResponse(String response) {
        latestResponse = response;
    }

    /**
     * Gets the latest response generated by the Ui.
     *
     * @return The latest response.
     */
    public String getLatestResponse() {
        return latestResponse;
    }
}
