package model;

/**
 * Represents a response generated by BotManager.
 *
 * @author dwsc37
 */
public class Response {
    private final String message;
    private final boolean isTerminating;

    /**
     * Constructor for a Response.
     *
     * @param message Response message.
     * @param isTerminating Whether the response is terminating.
     */
    public Response(String message, boolean isTerminating) {
        this.message = message;
        this.isTerminating = isTerminating;
    }

    public String getMessage() {
        return message;
    }

    public boolean isTerminating() {
        return isTerminating;
    }
}
