package mahesh;

import java.io.IOException;

import mahesh.command.Command;
import mahesh.util.MaheshException;
import mahesh.util.Parser;
import mahesh.util.Storage;
import mahesh.util.TaskList;

/**
 * Represents the main application class for managing tasks.
 * It initializes the application, processes user input, and executes commands.
 */
public class Mahesh {

    /**
     * The relative path to the file used for storing tasks.
     */
    private String path = "./data/mahesh.txt";
    private Storage store;
    private TaskList list;

    /**
     * Constructs a Mahesh object with the specified file path for storing tasks.
     *
     * @param path the optional relative path to the file used for storing tasks
     */
    public Mahesh(String path) {
        assert path != null : "Path should not be null";
        this.path = path;
        initializeStorage();
        assert this.store != null : "Storage should be initialized";
        assert this.list != null : "TaskList should be initialized";
    }

    /**
     * Constructs a Mahesh object with the default file path for storing tasks.
     */
    public Mahesh() {
        initializeStorage();
    }

    /**
     * Initializes the storage and retrieves data.
     */
    private void initializeStorage() {
        this.store = new Storage(this.path);
        try {
            this.list = store.retrieveData();
        } catch (IOException e) {
            this.list = new TaskList();
        }
        assert this.store != null : "Storage should be initialized";
        assert this.list != null : "TaskList should be initialized";
    }

    /**
     * Generates a response for the user's chat message.
     *
     * @param input the user's chat message
     * @return the response generated by executing the parsed command
     */
    public String getResponse(String input) {
        Parser parserObj = new Parser(list, store);
        try {
            Command command = parserObj.parse(input);
            return executeCommand(command);
        } catch (MaheshException err) {
            return err.getMessage();
        }
    }

    /**
     * Executes the given command and returns the response.
     *
     * @param command the command to be executed
     * @return the response generated by executing the command
     */
    private String executeCommand(Command command) {
        if (command != null) {
            return command.execute();
        } else {
            return "Unknown command";
        }
    }
}
