/**
 * This code has been refined with the assistance of Copilot to comply with the Java Style Guide.
 * Documentation comments have been generated by Copilot.
 * For further information, please refer to the Academic Declarations.
 */
package nathanbot.tasks;

import java.io.Serializable;

/**
 * Represents a task with a description and completion status.
 * Parent class of Deadline, Event, and Todo.
 */
public class Task implements Serializable {
    private static final long serialVersionUID = 1L;
    private final String description;
    private boolean isDone;
    private String tag;

    /**
     * Constructs a Task with the specified description.
     *
     * @param description The description of the task.
     * @param tag The tag of the task.
     */
    public Task(String description) {
        this.description = description;
    }

    /**
     * Marks the task as done.
     */
    public void markAsDone() {
        isDone = true;
    }

    /**
     * Sets the tag.
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * Marks the task as not done.
     */
    public void unmarkAsDone() {
        isDone = false;
    }

    /**
     * Returns a string representation of the task, including its completion status and description.
     *
     * @return A string representation of the task.
     */
    @Override
    public String toString() {
        String tagString = (tag != null && !tag.isEmpty()) ? "[" + tag + "] " : " ";
        return (isDone ? "[X] " : "[ ]") + tagString + description;
    }
}
