package bottleopener.myapp;

import bottleopener.task.Tasklist;
import bottleopener.ui.Ui;

/**
 * Represents the BottleOpener chatbot that handles user interactions, processes commands,
 * and maintains the state of tasks. It integrates with storage and user interface components
 * to provide a responsive and functional chatbot experience.
 */
public class BottleOpener {
    private static final String BOT_NAME = "BottleOpener";
    private static final String FILE_PATH = "data/BottleOpener.txt";
    private final Storage storage;
    private final Ui ui;
    private final Tasklist tasks;
    private boolean hasExited;

    /**
     * Constructs a BottleOpener instance with initial settings.
     * Initializes the task list, storage, and user interface components.
     * Loads previously saved tasks from storage.
     */
    public BottleOpener() {
        Tasklist tasklist = new Tasklist();
        this.storage = new Storage(FILE_PATH);
        this.ui = new Ui(BOT_NAME);
        this.tasks = storage.load(tasklist);

        assert this.storage != null : "Storage initialisation failed";
        assert this.ui != null : "Ui initialisation failed";
        assert this.tasks != null : "Tasklist loading from storage failed";

        this.hasExited = false;
    }

    /**
     * Processes the user input, updates the task list, and returns the response from the bot.
     * Saves the current state of tasks to the storage before processing the user input.
     *
     * @param userInput The input provided by the user.
     * @return The response message generated by the bot.
     */
    public String getResponse(String userInput) {
        storage.save(tasks);
        Parser parser = new Parser(userInput, this.tasks, this.ui);
        assert parser != null : "Parser initialisation failed";

        String botMessage = parser.execute();
        this.hasExited = parser.checkExit();
        return botMessage;
    }

    /**
     * Checks if the bot has exited the chat session.
     *
     * @return {@code true} if the bot has exited; {@code false} otherwise.
     */
    public boolean hasExited() {
        return this.hasExited;
    }

}
