package bottleopener.myapp;

import bottleopener.task.Tasklist;

/**
 * Represents the BottleOpener chatbot that handles user interactions, processes commands,
 * and maintains the state of tasks.
 */
public class BottleOpener {
    private static final String FILE_PATH = "data/BottleOpener.txt";
    private final Storage storage;
    private final Tasklist tasks;
    private boolean hasExited;

    /**
     * Constructs a BottleOpener instance with initial settings.
     * Initializes the task list and storage.
     * Loads previously saved tasks from storage.
     */
    public BottleOpener() {
        Tasklist tasklist = new Tasklist();
        this.storage = new Storage(FILE_PATH);
        this.tasks = storage.load(tasklist);
        this.hasExited = false;
    }

    /**
     * Processes the user input, updates the task list, and returns the response from the bot.
     * Saves the current state of tasks to the storage before processing the user input.
     *
     * @param userInput The input provided by the user.
     * @return The response message generated by the bot.
     */
    public String getResponse(String userInput) {
        storage.save(tasks);
        Parser parser = new Parser(userInput, this.tasks);
        String botMessage = parser.runParser();
        this.hasExited = parser.checkExit();
        return botMessage;
    }

    /**
     * Checks if the bot has exited the chat session.
     *
     * @return {@code true} if the bot has exited; {@code false} otherwise.
     */
    public boolean hasExited() {
        return this.hasExited;
    }

}
