package spiderman;

/**
 * Handles the parsing of user input and the execution of corresponding commands.
 */
public class Parser {
    protected static boolean isExit = false;

    /**
     * Parses the user input and executes the appropriate command based on the input.
     *
     * @param input The full user input string.
     * @param tasks The TaskList object that contains all current tasks.
     * @return The response string generated by the executed command.
     */
    public static String parseInput(String input, TaskList tasks) {
        String[] splitInput = input.split("\\s+");
        String[] splitInputByCommand = input.split("/");

        Command command = new Command();

        return switch (splitInput[0]) {
            case "todo" -> command.todo(splitInputByCommand, tasks);
            case "deadline" -> command.deadline(splitInputByCommand, tasks);
            case "event" -> command.event(splitInputByCommand, tasks);
            case "delete" -> command.delete(splitInput, tasks);
            case "list" -> command.list(tasks);
            case "find" -> command.find(input, tasks);
            case "mark" -> command.mark(splitInput, tasks);
            case "unmark" -> command.unmark(splitInput, tasks);
            case "bye" -> {
                isExit = true;
                yield command.bye();
            }
            default -> "Sorry, I do not understand what you mean. " +
                    "Check the README file for the list of known actions!";
        };
    }

    /**
     * Checks if the "bye" command was issued to exit the application.
     *
     * @return True if the application should exit, false otherwise.
     */
    public static boolean isExit() {
        return isExit;
    }
}
