package bob;

import storage.Storage;
import ui.UI;
import ui.Parser;
import ui.BotException;

/**
 * The Bob class is the main entry point for the Bob application.
 * It initializes the user interface and storage, and processes user input to generate responses.
 */
public class Bob {

    public UI ui = new UI();
    public Storage storage = new Storage("src/main/Data/save.txt");

    /**
     * Processes the user's input and returns a response.
     *
     * @param userInput The input entered by the user.
     * @return The response generated by parsing the user input.
     */
    public String getResponse(String userInput) {
        return Parser.parse(userInput, this.storage);
    }
}


