package utilities;

import tasks.ToDos;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

// Assumes the data file is based on the default generated by runtest
public class TaskListTest {
    private static final String FILE_PATH = "tasks/data.txt";
    private static final String ACTUAL_STRING = "1.[T][ ]  borrow book \n"
            + "2.[E][X]  project meeting from: Dec 29 2024 12:00 to: Dec 29 2024 17:00 \n"
            + "3.[T][ ]  borrow notes";

    private Storage store = new Storage(FILE_PATH);

    @Test
    public void manipulateListTest() {
        TaskList tl = new TaskList(this.store);
        // Check for addition
        tl.addToTaskList(new ToDos("run errands"), "run errands");
        assertEquals(5, tl.getSize());

        // Check for removal
        tl.removeFromTaskList(1);
        assertEquals(4, tl.getSize());

        // Check for updating of status, and printing of list
        tl.updateTaskListStatus(1, true);
        tl.removeFromTaskList(3);
        tl.updateTaskListStatus(2, false);
        assertEquals(ACTUAL_STRING, tl.toString().strip());
    }
}
