package qwerty;

import java.util.HashMap;
import java.util.Scanner;

import qwerty.command.ByeCommand;
import qwerty.command.Command;
import qwerty.command.DeadlineCommand;
import qwerty.command.DeleteCommand;
import qwerty.command.EmptyCommand;
import qwerty.command.EventCommand;
import qwerty.command.FindCommand;
import qwerty.command.ListCommand;
import qwerty.command.MarkCommand;
import qwerty.command.SortCommand;
import qwerty.command.TodoCommand;
import qwerty.command.UnknownCommand;
import qwerty.command.UnmarkCommand;

/**
 * This class encapsulates a Parser that parses command line inputs from the user.
 * The parser receives raw string inputs and returns the corresponding Command object
 * created with the given input arguments.
 */
public class Parser {
    /**
     * Returns a map of parameter-argument pairs as strings.
     * The map is generated from parsing the argument string after the main command.
     *
     * @param additionalArgs String containing arguments input from the user.
     * @return A hashmap containing parameters and their arguments
     */
    public static HashMap<String, String> parseArgs(String additionalArgs) {
        HashMap<String, String> map = new HashMap<>();

        // extract first argument separately because it has no identifier
        String[] argSplits = additionalArgs.split(" /", 2);
        map.put("main", argSplits[0].isEmpty() ? null : argSplits[0]);

        if (argSplits.length < 2) {
            return map; // no additional parameters to parse
        }

        Scanner scanner = new Scanner(argSplits[1]).useDelimiter(" /");

        // extract additional parameters and their arguments
        while (scanner.hasNext()) {
            String[] params = scanner.next().split(" ", 2);

            // only create entry for a parameter if its arguments are given
            if (params.length > 1) {
                map.put(params[0], params[1]);
            }
        }
        return map;
    }

    /**
     * Returns a command object generated by parsing the raw command line input.
     *
     * @param rawInput String input by the user.
     * @return The command object.
     */
    public static Command parse(String rawInput) {

        // separate command keyword from argument string
        String[] firstSplits = rawInput.split(" ", 2);
        String commandWord = firstSplits[0];

        // extract argument hashmap from argument string
        String argumentString = firstSplits.length > 1 ? firstSplits[1] : ""; // empty string for no args
        HashMap<String, String> args = Parser.parseArgs(argumentString);

        return switch (commandWord) {
        case "" -> new EmptyCommand(args);
        case "bye" -> new ByeCommand(args);
        case "list" -> new ListCommand(args);
        case "mark" -> new MarkCommand(args);
        case "unmark" -> new UnmarkCommand(args);
        case "todo" -> new TodoCommand(args);
        case "deadline" -> new DeadlineCommand(args);
        case "event" -> new EventCommand(args);
        case "delete" -> new DeleteCommand(args);
        case "find" -> new FindCommand(args);
        case "sort" -> new SortCommand(args);
        default -> new UnknownCommand(args);
        };
    }
}
