package lexi.command;

import lexi.exception.LexiException;
import lexi.storage.Storage;
import lexi.task.Task;
import lexi.task.TaskList;
import lexi.ui.Ui;

/**
 * Represents a command to add a task to the task list.
 * When executed, this command adds the specified task, updates the storage,
 * and displays a confirmation message to the user.
 */
public class AddCommand extends Command {
    private final Task task;
    private String response;

    /**
     * Constructs an AddCommand with the specified task.
     *
     * @param task The task to be added to the task list.
     */
    public AddCommand(Task task) {
        // Precondition: Task object must not be null
        assert task != null : "Task cannot be null.";
        this.task = task;
    }

    /**
     * Executes the add command, adding the specified task to the task list.
     * The task list and storage are updated, and a confirmation message is displayed to the user.
     *
     * @param tasks   The list of tasks.
     * @param ui      The UI object to interact with the user.
     * @param storage The storage to update the task list.
     * @throws LexiException If an error occurs while updating the storage.
     */
    @Override
    public void execute(TaskList tasks, Ui ui, Storage storage) throws LexiException {
        // Precondition assertions
        assert tasks != null : "TaskList cannot be null.";
        assert ui != null : "UI object cannot be null.";
        assert storage != null : "Storage object cannot be null.";

        tasks.addTask(task);

        // Post condition: The task list size should increase by 1 after adding the task
        assert tasks.getSize() > 0 : "Task list size should increase after adding a task.";

        storage.updateStorage(tasks.getTasks());

        int taskSize = tasks.getSize();
        response = ui.showAddMessage(task, taskSize);

        // Post condition: Response should be a non-null, non-empty string
        assert response != null && !response.isEmpty() : "Response should be a non-null, non-empty string.";
    }

    /**
     * Returns the name of the command.
     *
     * @return The string "ADD".
     */
    @Override
    public String getCommandName() {
        return "ADD";
    }

    /**
     * Returns the response message generated by the command execution.
     *
     * @return The response message.
     */
    @Override
    public String getString() {
        return response;
    }
}
