package lexi.command;

import lexi.exception.LexiException;
import lexi.storage.Storage;
import lexi.task.Task;
import lexi.task.TaskList;
import lexi.ui.Ui;

/**
 * Represents a command to delete a task from the task list.
 * When executed, this command removes a task based on its position in the list.
 */
public class DeleteCommand extends Command {
    private final int taskNumber;
    private String response;

    /**
     * Constructs a DeleteCommand with the specified task number.
     *
     * @param taskNumber The index of the task to be deleted. It must be greater than 0.
     */
    public DeleteCommand(int taskNumber) {
        // Precondition: Task number must be greater than 0
        assert taskNumber > 0 : "Task number must be greater than 0.";
        this.taskNumber = taskNumber;
    }

    /**
     * Executes the delete command, removing the specified task from the task list.
     * If the task is successfully deleted, the task list and storage are updated, and a confirmation message is shown.
     *
     * @param tasks   The list of tasks.
     * @param ui      The UI object to interact with the user.
     * @param storage The storage to update the task list.
     * @throws LexiException If the task number is invalid (i.e., if the task does not exist).
     */
    @Override
    public void execute(TaskList tasks, Ui ui, Storage storage) throws LexiException {
        // Assertions for preconditions
        assert tasks != null : "Task list cannot be null.";
        assert ui != null : "UI object cannot be null.";
        assert storage != null : "Storage object cannot be null.";

        // Check if the task number is within valid bounds
        if (taskNumber <= 0 || taskNumber > tasks.getSize()) {
            throw new LexiException("You can't delete a task that doesn't exist.");
        }

        Task removedTask = tasks.deleteTask(taskNumber - 1);

        // Assertion to ensure the task was removed correctly
        assert removedTask != null : "The removed task should not be null.";

        response = ui.showDeleteMessage(removedTask, tasks.getSize());

        // Assertion to ensure the response is set correctly
        assert response != null && !response.isEmpty() : "Response should be a non-null, non-empty string.";

        storage.updateStorage(tasks.getTasks());
    }

    /**
     * Returns the name of the command.
     *
     * @return The string "DELETE".
     */
    @Override
    public String getCommandName() {
        return "DELETE";
    }

    /**
     * Returns the response message generated by the command execution.
     *
     * @return The response message.
     */
    @Override
    public String getString() {
        return response;
    }
}
