name: Java CI

on: [push, pull_request]

jobs:
  # Build Stage
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk+fx

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Print system information
        run: |
          java -version
          uname -a
          echo "Locale: $(locale)"
          echo "Time Zone: $(date +'%Z %z')"

      - name: Build the project
        run: ./gradlew build --info
